### ISSUE TITLE
Installer not progressing install/updating liveries

### ISSUE THREAD

**Issue by Altycoder** [headwindsim/installer#3]
### Installer Version

v1.4.1

### Describe the bug

Updating or re-installing A339X livery package (release) does nothing, spinning circles with nothing happening

I'm on Win 11 Pro with latest installer installed.

### Expected behavior

Updated liveries are downloaded

### Steps to reproduce

1. Select A339X Livery Package. Release (v0.4.1 pre-selected).
2. Click install, nothing happens, spinning circle.....

### Additional info (optional)

I have tried updating, uninstalling and re-installing the liveries but nothing happens either way

**Comment by michael60634** [comment]
I'm having the same issue, a year later.

**Comment by Revyn112** [comment]
Please uninstall the current version and install the release Version (1.5.0) again: https://cdn.headwindsim.net/installer/release/Headwind_Installer_Setup.exe
