### ISSUE TITLE
Installer not installing Headwind Simulation products due to "Undefined URL"

### ISSUE THREAD

**Issue by syed-a-s** [headwindsim/installer#4]
### Installer Version

v1.4.9

### Describe the bug

Updating or installing any product from Headwind Simulations does nothing because of undefined URLs to the products. This causes the installer to be stuck in a spinning circle. I am able to install products from other publishers, such as the 787 textures from Horizon Simulations. 

### Expected behavior

After clicking download, it should show the user the package size and prompt the user to install. 

### Steps to reproduce

1. Click download on any product provided by Headwind Simulations (A339X, SU95X, Livery Packages, etc)

### References (optional)

![undefined url](https://github.com/user-attachments/assets/466bfda2-27b7-4126-8131-4d349ccba106)
When trying to download the A339X, I get an undefined URL, and the download spinner is stuck until I refresh. 

![filenotfound](https://github.com/user-attachments/assets/7b18e4d1-c211-48f8-8bfb-495dd50e43de)
![404notfound](https://github.com/user-attachments/assets/495a7d31-c669-4308-b9c8-ca13245d4eed)
I found the _productions.json_ file in my local files. I noticed that when visiting the "url" key value inside the "track" object through my browser, I get a _File Not Found_ page. However, when visiting the "url" key from Horizon Simulations, I get a "404 Not Found" page.

### Additional info (optional)

I got the Headwind installer because I wanted to try out the pre-release version, but I when I tried to download it, it got stuck. I am thinking, maybe the "url" key inside the "track" object needs to be updated in _products.json_? I'm not sure though; I don't know what's really going on in the background. I have also seen in the FlyByWire reported issues that this could be an issue caused by my ISP blocking out CDN, but then I shouldn't be able to download Horizon Simulation products too, right? Still, I'm not sure though. 

Thank you all for all you do! I love that there is high-quality free-ware addons for MSFS.

**Comment by Revyn112** [comment]
Uninstall Headwind Installer. Then Download this Dev Version: https://cdn.headwindsim.net/installer/dev/Headwind_Installer_Setup.exe and install it with Admin rights. Please report back if the issue is fixed or not.

**Comment by syed-a-s** [comment]
Yes, it seems I am able to download Headwind Simulation products with the dev version. Thank you for helping!

**Comment by Revyn112** [comment]
> Yes, it seems I am able to download Headwind Simulation products with the dev version. Thank you for helping!

Alright, thanks for feedback, we've updated the release version. Please uninstall the dev version and install the release Version again: https://cdn.headwindsim.net/installer/release/Headwind_Installer_Setup.exe

The dev version will not receiving any updates, so you need to do switch manually the version to get any updates in the future again.
